Improved grouping in microtiming
scireum/sirius-db pull request #376
Opened 2020-10-22 12:44 UTC by andyHa

As we currently output all filter values in Microtiming, each query is reported for itself.

For the microtiming we rather want an aggregation here and therefore only output the
fields being filtered on. Therefore common queries are aggregated and the reporting
improves. The raw querie can sill be retrieved by enabling fine logging for the DB logger.

2020-10-22 12:47 UTC, sabieber approved these changes

2020-10-22 17:25 UTC, bwiedmann commented on src/main/java/sirius/db/jdbc/SmartQuery.java
> +                    w.submitMicroTiming("OMA", "COUNT: "+ compiler.getQuery());
Codeformat? Missing spaces?

2020-10-22 17:25 UTC, bwiedmann approved these changes

2020-10-22 18:15 UTC, mkeckmkeck approved these changes

2020-10-23 06:51 UTC, qw3ry approved these changes

2020-10-23 08:11 UTC, meg1502 requested changes

2020-10-23 08:11 UTC, meg1502 commented on src/main/java/sirius/db/jdbc/GeneratedStatement.java
> +            watch.submitMicroTiming("SQL", microtimingKey()+": "+ sql);
```suggestion
            watch.submitMicroTiming("SQL", microtimingKey()+": " + sql);
```

2020-10-23 08:11 UTC, meg1502 commented on src/main/java/sirius/db/jdbc/SmartQuery.java
> +                    w.submitMicroTiming("OMA", "COUNT: "+ compiler.getQuery());
```suggestion
                    w.submitMicroTiming("OMA", "COUNT: " + compiler.getQuery());
```

2020-10-23 08:11 UTC, meg1502 commented on src/main/java/sirius/db/jdbc/WrappedPreparedStatement.java
> +        w.submitMicroTiming("SQL","PreparedStatement: "+ sql);
```suggestion
        w.submitMicroTiming("SQL","PreparedStatement: " + sql);
```

2020-10-23 08:11 UTC, meg1502 commented on src/main/java/sirius/db/jdbc/SmartQuery.java
> +                    w.submitMicroTiming("OMA", "ITERATE: "+ compiler.getQuery());
```suggestion
                    w.submitMicroTiming("OMA", "ITERATE: " + compiler.getQuery());
```

2020-10-23 08:25 UTC, merged