Removes a horrible and error prone API for MongoDB.
scireum/sirius-db pull request #391
Opened 2020-12-21 19:34 UTC by andyHa

2020-12-21 20:47 UTC, idlira requested changes
mini typo

2020-12-21 20:47 UTC, idlira commented on src/main/java/sirius/db/mongo/Updater.java
> +     * Note that this is a legacy flag and will not be honery by neither {@link #executeForOne(String)} nor
```suggestion
     * Note that this is a legacy flag and will not be honored by neither {@link #executeForOne(String)} nor
```

2020-12-21 22:33 UTC, idlira approved these changes

2020-12-22 07:52 UTC, qw3ry approved these changes

2020-12-23 11:45 UTC, merged