BREAKING: Gives all properties a default value determined by their initial value
scireum/sirius-db pull request #439
Opened 2021-08-19 17:02 UTC by meg1502

### BREAKING: Gives all properties a default value determined by their initial value

The biggest change from this is that all primitive number fields have a default value of '0' if not initialized with another number.
Previously they produced an IllegalArgumentException when they had no default value.
This means, for non-nullable fields that should not have a default value but should produce an error when left empty, a non-primitve datatype should be used. Then they will be properly transformed from import/webcontext to null and produce an error on save.

Please note that for primitive booleans this was already implemented, but if you used the default value directly, the actual default value has changed from '0' to 'false'.

### BREAKING:Changes Property#defaultValue type from String to Value

Instead of a string that doubles as a value used for the column default value, the defaultValue will now hold an Object that represents the property wrapped in a Value, or Value.EMPTY if no default Value is present. JDBC Column default value can be retrieved via a new method.

To make it more universal, DefaultValue Annotations are now transformed like machine input (Property#transformValueFromImport), so existing DefaultValue annotations might need to be adjusted, especially times,dates and booleans.

2021-08-19 17:36 UTC, idlira requested changes

2021-08-19 17:36 UTC, idlira commented on src/main/java/sirius/db/mixing/Property.java
> +            Object initalValue = getValue(getDescriptor().getReferenceInstance());
typo: initialValue

2021-08-19 17:36 UTC, idlira commented on src/test/java/sirius/db/mixing/properties/DefaultValuesSpec.groovy
> +        propertyName            | excpectedDefault
typo: expected

2021-08-20 09:26 UTC, idlira approved these changes

2021-08-20 12:53 UTC, qw3ry approved these changes
- There seems to be quite a lot to migrate. A short "Migration Guide" would be helpful
- Would `@DefaultValue(Value.EMPTY) int x` also work to get a non-nullable field without default value?

2021-08-20 13:28 UTC, meg1502 commented
- I can write a short guide, it isn't that much as the Default Value Annotation isn't that much used, the main thing will be ensuring all non-nullable fields that should report an error when saving instead of applying a default are non-primitive
- Then we would be back to square 1, the main point of this change is that primitve fields are no longer used for this case, as primitive fields will always produce an illegalArgumentException instead of the "can't be null" error, as the field need to be able to hold the null value between transforming from user input/import and the saving of the entity where the nullability check happens.

2021-08-20 15:57 UTC, andyHa approved these changes

2021-08-20 15:58 UTC, andyHa commented
Are any @DefaultValue annotations present anyway? It would be much safer and more consistent to simply initialize the
Java field anyway(?)

2021-08-23 08:09 UTC, merged