Millisecond Precision
scireum/sirius-db pull request #477
Opened 2021-11-26 16:34 UTC by jakobvogel

2021-11-26 16:52 UTC, sabieber approved these changes

2021-11-26 17:00 UTC, andyHa requested changes

2021-11-26 17:00 UTC, andyHa commented on src/main/java/sirius/db/mixing/EntityDescriptor.java
> +            return sourceDateTime.truncatedTo(ChronoUnit.MILLIS).equals(targetDateTime.truncatedTo(ChronoUnit.MILLIS));
Maybe we need a marker annotation or s.th. the like

2021-11-26 21:26 UTC, andyHa approved these changes

2021-11-29 06:34 UTC, mkeckmkeck approved these changes

2021-11-29 07:36 UTC, qw3ry approved these changes

2021-11-29 07:36 UTC, qw3ry commented on src/main/java/sirius/db/mixing/EntityDescriptor.java
> +            }
Would be more clean if we could put this into the DB specific stuff, but I don't know if there is a place where this fits nicely.

2021-11-29 07:56 UTC, sabieber approved these changes

2021-11-29 08:21 UTC, idlira approved these changes

2021-11-29 09:18 UTC, merged