SIRI-799 Warn on bad usages of streamBlockwise
scireum/sirius-db pull request #561
Opened 2023-04-26 14:52 UTC by qw3ry

2023-05-09 06:38 UTC, sabieber approved these changes

2023-05-09 06:43 UTC, idlira approved these changes

2023-05-09 09:19 UTC, andyHa requested changes

2023-05-09 09:19 UTC, andyHa commented on src/main/java/sirius/db/jdbc/SmartQuery.java
> +        private List<Object> getValues(E entity) {
fetchOrderByValues or the like

2023-05-11 08:28 UTC, sabieber approved these changes

2023-05-11 08:42 UTC, andyHa commented on src/main/java/sirius/db/jdbc/SmartQuery.java
> +                OMA.LOG.WARN(
throw illegal state or the like

2023-05-11 09:55 UTC, andyHa approved these changes

2023-05-11 09:56 UTC, merged