JUnit: Migrates SmartQueryNightly-/ and SmartQuerySorting to Kotlin
scireum/sirius-db pull request #627
Opened 2024-02-01 15:10 UTC by scireum-mbo

Fixes: OX-10357

2024-02-01 15:11 UTC, mko-sci approved these changes

2024-02-02 08:27 UTC, sabieber requested changes

2024-02-02 08:27 UTC, sabieber commented on src/test/kotlin/sirius/db/jdbc/SmartQuerySortingTest.kt
> +        }
**Required:** I think this needs to be annotated with AfterAll so it is actually executed by jUnit

2024-02-05 14:35 UTC, sabieber approved these changes

2024-02-05 14:40 UTC, mkeckmkeck commented on src/test/kotlin/sirius/db/jdbc/SmartQueryKotlinTest.kt
> +        FieldUtils.writeField(newOMA, "schema", mockk<Schema>(), true)
Why do ne need reflection and spyk? Can't we mock this with spyk?

2024-02-05 14:45 UTC, mkeckmkeck commented on src/test/kotlin/sirius/db/jdbc/SmartQueryKotlinTest.kt
> +        FieldUtils.writeField(newOMA, "schema", mockk<Schema>(), true)
got it :-)

2024-02-05 14:45 UTC, mkeckmkeck approved these changes

2024-02-06 08:50 UTC, merged